version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: order_management_db
    environment:
      MYSQL_ROOT_PASSWORD: orderapp123
      MYSQL_DATABASE: order_management
      MYSQL_USER: appuser
      MYSQL_PASSWORD: orderapp123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  order-management-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/order_management
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: orderapp123
    depends_on:
      - mysql
    ports:
      - "8080:8080"

volumes:
  mysql_data:
